apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: barabis/multi-client
          resources:              
            # requests:
            #   cpu: 50m
            #   memory: 50Mi
            limits:
              memory: "256Mi"
              cpu: "350m"
          ports:
            - containerPort: 3000
